misc pipeline changes

diff --git a/.github/workflows/tf-drift.yaml b/.github/workflows/tf-drift.yaml
--- a/.github/workflows/tf-drift.yaml
+++ b/.github/workflows/tf-drift.yaml
@@ -1,7 +1,7 @@
 name: "Terraform Drift Detection"
 
 on:
-  workflow_dispatch: 
+  workflow_dispatch:
   schedule:
     - cron: "0 4 * * *" # runs nightly at 4:00 am
 
@@ -20,85 +20,84 @@ env:
 
 jobs:
   terraform-drift:
-    name: 'Terraform Drift'
+    name: "Terraform Drift"
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         target: [prod, nonprod]
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-      with:
-        terraform_version: $TERRAFORM_VERSION
-        terraform_wrapper: false
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: $TERRAFORM_VERSION
+          terraform_wrapper: false
 
-    - name: Terraform init
-      id: init
-      env:
-        TF_ENV: ${{ matrix.target }}
-      run: terraform init -backend-config="key=$TF_ENV.tfstate" -backend-config="container_name=$TF_ENV-branching-state"
+      - name: Terraform init
+        id: init
+        env:
+          TF_ENV: ${{ matrix.target }}
+        run: terraform init -backend-config="key=$TF_ENV.tfstate" -backend-config="container_name=$TF_ENV-branching-state"
 
+      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      - name: Terraform plan
+        id: tf-plan
+        env:
+          TF_ENV: ${{ matrix.target }}
+        run: |
+          export exitcode=0
+          terraform plan -var-file=$TF_ENV.tfvars -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-    - name: Terraform plan
-      id: tf-plan
-      env: 
-        TF_ENV: ${{ matrix.target }}
-      run: |
-        export exitcode=0
-        terraform plan -var-file=$TF_ENV.tfvars -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-        
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
-        
-    # Create string output of Terraform Plan
-    - name: Create String Output
-      id: tf-plan-string
-      run: |
-        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-        
-        delimiter="$(openssl rand -hex 8)"
-        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-        echo "" >> $GITHUB_OUTPUT
-        echo '```terraform' >> $GITHUB_OUTPUT
-        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-        echo '```' >> $GITHUB_OUTPUT
-        echo "</details>" >> $GITHUB_OUTPUT
-        echo "${delimiter}" >> $GITHUB_OUTPUT
-        
-    # Publish Terraform Plan as task summary
-    - name: Publish Terraform Plan to Task Summary
-      env:
-        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-      run: |
-        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+          if [ $exitcode -eq 1 ]; then
+            echo Terraform Plan Failed!
+            exit 1
+          else 
+            exit 0
+          fi
 
-    # If changes are detected, create a new issue
-    - name: Publish Drift Report
-      if: steps.tf-plan.outputs.exitcode == 2
-      uses: actions/github-script@v7
-      env:
-        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-        TF_ENV: ${{ matrix.target }}
-      with:
+      # Create string output of Terraform Plan
+      - name: Create String Output
+        id: tf-plan-string
+        run: |
+          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+
+          delimiter="$(openssl rand -hex 8)"
+          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+          echo "" >> $GITHUB_OUTPUT
+          echo '```terraform' >> $GITHUB_OUTPUT
+          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+          echo '```' >> $GITHUB_OUTPUT
+          echo "</details>" >> $GITHUB_OUTPUT
+          echo "${delimiter}" >> $GITHUB_OUTPUT
+
+      # Publish Terraform Plan as task summary
+      - name: Publish Terraform Plan to Task Summary
+        env:
+          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+        run: |
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+
+      # If changes are detected, create a new issue
+      - name: Publish Drift Report
+        if: steps.tf-plan.outputs.exitcode == 2
+        uses: actions/github-script@v7
+        env:
+          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+          TF_ENV: ${{ matrix.target }}
+        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const body = `${process.env.SUMMARY}`;
             const title = `Terraform Configuration Drift Detected in ${process.env.TF_ENV}`;
             const creator = 'github-actions[bot]'
-          
+
             // Look to see if there is an existing drift issue
             const issues = await github.rest.issues.listForRepo({
               owner: context.repo.owner,
@@ -134,16 +133,16 @@ jobs:
              })
             }
 
-    # If changes aren't detected, close any open drift issues
-    - name: Publish Drift Report
-      if: steps.tf-plan.outputs.exitcode == 0
-      uses: actions/github-script@v7
-      with:
+      # If changes aren't detected, close any open drift issues
+      - name: Publish Drift Report
+        if: steps.tf-plan.outputs.exitcode == 0
+        uses: actions/github-script@v7
+        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const title = `Terraform Configuration Drift Detected in ${process.env.TF_ENV}`;
             const creator = 'github-actions[bot]'
-          
+
             // Look to see if there is an existing drift issue
             const issues = await github.rest.issues.listForRepo({
               owner: context.repo.owner,
@@ -162,9 +161,9 @@ jobs:
                 issue_number: issue.number,
                 state: 'closed'
               })
-            } 
+            }
 
-    # Mark the workflow as failed if drift detected 
-    - name: Error on Failure
-      if: steps.tf-plan.outputs.exitcode == 2
-      run: exit 1
+      # Mark the workflow as failed if drift detected
+      - name: Error on Failure
+        if: steps.tf-plan.outputs.exitcode == 2
+        run: exit 1
